# === CartPole-v1 - GPU Accelerated (v2 - Tuned for Stability) ===
env_id: CartPole-v1
seed: 1
total_timesteps: 50000

# --- WORKLOAD & DEVICE (SCALED FOR GPU) ---
device: cuda
use_compile: true
float32_matmul_precision: high
num_envs: 1024
actor_hidden_sizes: [256, 256]
critic_hidden_sizes: [256, 256]

# --- LEARNING PARAMETERS (TUNED FOR LARGER NETWORK) ---
rollout_steps: 128
n_epochs: 10                  # <-- CHANGE: Increased epochs for better learning
minibatch_size: 16384
gamma: 0.99
gae_lambda: 0.98
clip_coef: 0.2
vf_coef: 0.5
ent_coef: 0.01
max_grad_norm: 0.5
activation: tanh
lr: 0.0003                   # <-- CHANGE: Reduced LR for stability
lr_anneal: ""

# --- STABILIZERS ---
adv_norm: true
use_value_clip: false
obs_norm: false