# === CartPole-v1 - CPU Baseline (Optimized for Learning) ===
env_id: CartPole-v1
seed: 1
total_timesteps: 50000

# --- WORKLOAD & DEVICE ---
device: cpu
num_envs: 8
actor_hidden_sizes: [64, 64]
critic_hidden_sizes: [64, 64]

# --- LEARNING PARAMETERS ---
rollout_steps: 128
n_epochs: 4
minibatch_size: 256
gamma: 0.99
gae_lambda: 0.98
clip_coef: 0.2
vf_coef: 0.5
ent_coef: 0.01
max_grad_norm: 0.5
activation: tanh
lr: 0.0005
lr_anneal: ""

# --- STABILIZERS ---
adv_norm: true
use_value_clip: false # Not needed for simple envs
obs_norm: false