# === Pendulum-v1 - GPU Accelerated (v2 - Tuned for Stability) ===
env_id: Pendulum-v1
seed: 1
total_timesteps: 300000

# --- WORKLOAD & DEVICE (SCALED FOR GPU) ---
device: cuda
use_compile: true
float32_matmul_precision: high
num_envs: 256
actor_hidden_sizes: [512, 512]
critic_hidden_sizes: [512, 512]

# --- LEARNING PARAMETERS (TUNED FOR LARGER NETWORK) ---
rollout_steps: 256
n_epochs: 20                  # <-- CHANGE: Increased epochs for better learning on the large batch
minibatch_size: 16384
gamma: 0.99
gae_lambda: 0.95
clip_coef: 0.2
vf_clip_coef: 0.2
ent_coef: 0.001
vf_coef: 0.5
max_grad_norm: 1.0
activation: tanh
lr: 0.0003                   # <-- CHANGE: Reduced LR for stability with the large network
lr_anneal: linear

# --- STABILIZERS ---
reward_scale: 0.1
obs_norm: true
adv_norm: true
use_value_clip: true
use_tanh_squash: true
target_kl: 0.02