env_id: CartPole-v1
seed: 1
total_timesteps: 100000
device: cuda
use_compile: true
use_amp: true
num_envs: 256
rollout_steps: 256
minibatch_size: 1024
actor_hidden_sizes: [256, 256]
critic_hidden_sizes: [256, 256]
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_coef: 0.2
vf_clip_coef: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
activation: tanh
lr: 0.0003
lr_anneal: linear
use_value_clip: true
adv_norm: true
use_tanh_squash: false
target_kl: 0.015
float32_matmul_precision: high