env_id: Pendulum-v1
seed: 1
total_timesteps: 300000
num_envs: 64
rollout_steps: 512
n_epochs: 10
minibatch_size: 4096
gamma: 0.99
gae_lambda: 0.95
clip_coef: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
lr: 0.0003
anneal_lr: true

device: auto
vector_env: sync
use_amp: true
use_compile: max-autotune
float32_matmul_precision: high
