# configs/ppo_pendulum_gpu.yaml
env_id: Pendulum-v1
seed: 1
total_timesteps: 600000
num_envs: 32
rollout_steps: 256         # 8192 steps/update
minibatch_size: 2048
n_epochs: 10
lr: 0.0003
clip_coef: 0.2
ent_coef: 0.0
gamma: 0.99
gae_lambda: 0.95
vf_coef: 0.5
max_grad_norm: 0.5
anneal_lr: true
device: auto
vector_env: sync
use_compile: max-autotune
float32_matmul_precision: high
