# configs/ppo_pendulum.yaml
env_id: Pendulum-v1
seed: 1
total_timesteps: 400000
num_envs: 16
rollout_steps: 128         # 2048 steps/update
minibatch_size: 1024
n_epochs: 10
lr: 0.0003
clip_coef: 0.2
ent_coef: 0.0
gamma: 0.99
gae_lambda: 0.95
vf_coef: 0.5
max_grad_norm: 0.5
anneal_lr: true
device: auto
vector_env: sync
use_compile: false
